# Generated by Django 5.0.7 on 2024-09-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('shift', models.CharField(choices=[('M', 'Morning'), ('D', 'Day')], max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'Course',
                'ordering': ['title'],
            },
        ),
    ]
