# Generated by Django 5.0.7 on 2024-09-03 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'Class',
                'ordering': ['course'],
            },
        ),
    ]
