# Generated by Django 5.0.7 on 2024-09-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_studentclass_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
