# Generated by Django 5.0.7 on 2024-09-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.course'),
        ),
    ]
