# Generated by Django 5.0.7 on 2024-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_studentclass_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentclass',
            table='student_class',
        ),
    ]
